version: "3"
services:
  app:
    build: .
    #command: make upgrade-db #gunicorn --access-logfile=logs/access.log --error-logfile=logs/errors.log app:app
    depends_on:
      - mysql
    links:
      - 'mysql:mysql'
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: 'mysql://avito:cosine-hedgehog@mysql:3306/avito_json?charset=utf8'
  mysql:
    image: mysql:5.7
    ports:
      - '32000:3306'
    environment:
      MYSQL_USER: avito
      MYSQL_PASSWORD: cosine-hedgehog
      MYSQL_DATABASE: avito_json
      MYSQL_ROOT_PASSWORD: ruODRkA3oXYejfw?0aPx
