version: "3"
services:
  app:
    build: .
    depends_on:
      - mysql
    links:
      - 'mysql:mysql'
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?charset=utf8"
  mysql:
    image: mysql:5.7
    ports:
      - "32000:${MYSQL_PORT}"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
