"""Add price field

Revision ID: ce37ec70774b
Revises: d486e941c5db
Create Date: 2019-12-29 15:10:22.895650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce37ec70774b'
down_revision = 'd486e941c5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('price', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'price')
    # ### end Alembic commands ###
